### ISSUE TITLE
Error when level up from 1 to 2

### ISSUE THREAD

**Issue by torputt** [renoth/factorio-alien-module#61] opened 2020-09-26 20:52 UTC
I got this error. This happened when level up from 1 to 2 (didn't happen from 0 to 1).

I unchecked almost every mod (except RSO and creative mode and and still got this error).

The mod Alien Loot Economy (1.1.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event alien-module::on_nth_tick(120)
LuaItemStack API call when LuaItemStack was invalid for read.
stack traceback:
	__alien-module__/control.lua:95: in function 'update_modules'
	__alien-module__/control.lua:375: in function <__alien-module__/control.lua:331>
stack traceback:
	[C]: in function '__index'
	__alien-module__/control.lua:95: in function 'update_modules'
	__alien-module__/control.lua:375: in function <__alien-module__/control.lua:331>

**Comment by ResidentOfKill** [comment] 2020-09-26 20:57
duplicate of #59

**Comment by renoth** [comment] 2020-09-27 07:33
Should be fixed in 1.1.4

**Closed by renoth** 2020-09-27 07:33 UTC
