### ISSUE TITLE
Non-recoverable error

### ISSUE THREAD

**Issue by Biowolf80** [renoth/factorio-alien-module#91] opened 2024-03-20 15:26 UTC
Not sure what's happening, installed this mod before played a good 12 hours. started a new map and now if i kill a big bug this code pops up and closes the game.  Also apologies is this is the incorrect place to post this.

The mod Alien Loot Economy (1.4.5) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event alien-module::on_entity_died (ID 4)
__alien-module__/control.lua:368: attempt to perform arithmetic on field '?' (a nil value)
stack traceback:
	__alien-module__/control.lua:368: in function <__alien-module__/control.lua:365>

**Comment by renoth** [comment] 2024-03-21 09:40
do you use any other mods?

**Comment by renoth** [comment] 2024-06-28 17:34
Duplicate of #99

**Closed by renoth** 2024-06-28 17:34 UTC
